app = "dexera-bff-dev"
primary_region = "iad"

[build]
dockerfile = "../../docker/bff.Dockerfile"

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
